spring:
#  profiles:
#    include:
#      - aws
  datasource:
    url: jdbc:mysql://mes-dev.cyyxmbrc9eeg.ap-northeast-2.rds.amazonaws.com:3306/mes-dev?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: SilverStar01!#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  h2:
    console:
      enabled: true
  server:
    port : 8081

    servelet:
      session:
        timeout: 30
      context-path : /swagger-ui.html
    ssl:
      enabled: true


  servlet:
     multipart:
       max-file-size:10MB
       max-request-size:10MB
#  couchbase:
#    env:
#      timeouts:

  freemarker:
    check-template-location: false

cloud:
  aws:
    credentials:
      accessKey: AKIAQFOAKXS7ACQ2KTMD
      secretKey: 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
    region:
      static: ap-northeast-2
    bucketName: mes-develop
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR