# Main
INSERT INTO `mes-dev`.MAIN_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN) VALUES (1, 0, '기준정보', 1, true);
-- Sub
INSERT INTO `mes-dev`.SUB_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, MAIN_NAVS_ID) VALUES (1, 0, '공통정보', 1, true, 1);
INSERT INTO `mes-dev`.SUB_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, MAIN_NAVS_ID) VALUES (2, 0, '품목정보', 2, true, 1);
INSERT INTO `mes-dev`.SUB_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, MAIN_NAVS_ID) VALUES (3, 0, '생산정보', 3, true, 1);
INSERT INTO `mes-dev`.SUB_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, MAIN_NAVS_ID) VALUES (4, 0, '품질정보', 4, true, 1);
INSERT INTO `mes-dev`.SUB_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, MAIN_NAVS_ID) VALUES (5, 0, '설비정보', 5, true, 1);
-- detail
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (1, 0, '코드마스터 등록', 1, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (2, 0, '사업장 등록', 2, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (3, 0, '공장 등록', 3, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (4, 0, '부서 등록', 4, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (5, 0, '직원(작업자) 등록', 5, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (6, 0, '거래처 등록', 6, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (7, 0, '비품관리', 7, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (8, 0, '판매처별 납품처', 8, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (9, 0, '단위 등록', 9, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (10, 0, '창고 등록', 10, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (11, 0, '휴일 등록', 11, true, 1);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID) VALUES (12, 0, '알림 등록', 12, true, 1);

INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (1, 0, '코드마스터 등록', 1, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (2, 0, '사업장 등록', 2, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (3, 0, '공장 등록', 3, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (4, 0, '부서 등록', 4, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (5, 0, '직원(작업자) 등록', 5, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (6, 0, '거래처 등록', 6, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (7, 0, '비품관리', 7, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (8, 0, '판매처별 납품처', 8, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (9, 0, '단위 등록', 9, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (10, 0, '창고 등록', 10, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (11, 0, '휴일 등록', 11, true, 1, null);
INSERT INTO `mes-dev`.DETAIL_NAVS (ID, LEVEL, NAME, ORDERS, USE_YN, SUB_NAVS_ID, PATH) VALUES (12, 0, '알림 등록', 12, true, 1, null);



